---
title: "AT5G45470 & AT545480 qPCR"
output: html.notebook
---

qPCR analysis and plots for my master thesis.

```{r}
require(ggplot2)
require(readxl)
require(dplyr)
```

Pfaffl method:

```{r}
plant <- c(rep("WTE-", 3), rep("WTE+", 3), rep("70E-", 3), rep("70E+", 3))
weight <- c(19.4, 19.8, 18.4, 17.4, 19.4, 18.2, 18.8, 16.2, 15.8, 19.2, 16.4, 18.1)
df <- data.frame(plant, weight)
df
```

```{r}
means <- df %>%
  group_by(plant) %>% 
  dplyr::summarise(weight = mean(weight))
means$error.bars <- c(0.72, 1.42, 1.63, 1.42)
means

bar_plot <- ggplot(df, aes(x = plant, y = weight, fill = plant)) +
  geom_bar(data=means, stat = "identity", alpha=0.8) +
  ggtitle("Waga 100 nasion w zależności od mutacji oraz inokulacji") +
  geom_point(alpha=0.8) +
  labs(x = "Grupa roślin", y = "Zmiana ekspresji genu") +
  scale_fill_manual(values = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C")) +
  theme(legend.position = "none", text = element_text(size = 20)) +
  geom_errorbar(data=means, aes(ymin=weight - error.bars, ymax=weight+error.bars), width = 0.25) +
  theme(panel.background = element_rect(fill = "white"),  # Białe tło
        panel.grid.major = element_line(color = "lightgrey"), 
        legend.title.align = 0.5,# Szare osie siatki
        panel.grid.minor = element_blank())  # Usunięcie siatki podrzędnej

bar_plot
```

```{r}
ggsave(filename = 'nasiona.png',plot = bar_plot, width = 12, height = 8)
```

```{r}
t.test.70 <- t.test(df$weight[1:3],df$weight[4:6], var.equal = TRUE)
t.test.70
```

```{r}
t.test.80 <- t.test(df$weight[7:9],df$weight[10:12], var.equal = TRUE)
t.test.80
```
