---
title: "AT5G45470 pot cultures"
output: html_document
---

AT5G45470 plots for the pot cultures

```{r}
require(ggplot2)
require(readODS)
require(dplyr)
require(car)
require(dotenv)
```

```{r}
load_dot_env(file = ".env")
```


```{r}  
path <- Sys.getenv("MY_PATH")
path
```

```{r}
kwit_path <- file.path(path, "pot_cultures/data/kwitnienie70.ods")
liscie_path <- file.path(path, "pot_cultures/data/liscie70.ods")
```

```{r}
kwit <- read_ods(kwit_path)
liscie <- read_ods(liscie_path)
```

```{r}
kwit_plot <- ggplot(kwit, aes(x = DNI)) +
    geom_line(aes(y = X70minus, color = "AT5G45470 E-"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = X70minus, color = "AT5G45470 E-"), shape = 16, size = 3) +
    geom_line(aes(y = X70plus, color = "AT5G45470 E+"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = X70plus, color = "AT5G45470 E+"), shape = 16, size = 3) +
    geom_line(aes(y = Wtminus, color = "WT E-"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = Wtminus, color = "WT E-"), shape = 16, size = 3) +
    geom_line(aes(y = Wtplus, color = "WT E+"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = Wtplus, color = "WT E+"), shape = 16, size = 3) +
    ggtitle("Kwitnienie w czasie") +  # Tytuł wykresu
    labs(x = "Dni", y = "Ilość roślin posiadających kwiat") +
    scale_y_continuous(limits =c(0, 25)) +
    scale_color_manual(
        values = c(
            "AT5G45470 E-" = "#A6CEE3",
            "AT5G45470 E+" = "#1F78B4",
            "WT E-" = "#B2DF8A",
            "WT E+" = "#33A02C"
        ),
        name = "",
        labels = c(
            "AT5G45470 E-" = "AT5G45470 E-",
            "AT5G45470 E+" = "AT5G45470 E+",
            "WT E-" = "WT E-",
            "WT E+" = "WT E+"
        )
    ) +  # Definicja etykiety legendy
    theme(legend.position = "top", text = element_text(size = 20)) +
    theme(plot.title = element_text(hjust = 0.5)) + # Środkowanie tytułu
    theme(
        panel.background = element_rect(fill = "white"),  # Białe tło
        panel.grid.major = element_line(color = "lightgray", size = 0.5), # Szare linie siatki
        panel.grid.minor = element_blank()  # Wyłącz linie siatki pomocniczej
    )
```

```{r}
ggsave(filename = file.path(path, 'figures/plots/kwitnienie70.png'), plot = kwit_plot, width = 12, height = 8)
```

```{r}
liscie_plot <- ggplot(liscie, aes(x = DNI)) +
    geom_line(aes(y = X70minus, color = "AT5G45470 E-"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = X70minus, color = "AT5G45470 E-"), shape = 16, size = 3) +
    geom_line(aes(y = X70plus, color = "AT5G45470 E+"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = X70plus, color = "AT5G45470 E+"), shape = 16, size = 3) +
    geom_line(aes(y = Wtminus, color = "WT E-"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = Wtminus, color = "WT E-"), shape = 16, size = 3) +
    geom_line(aes(y = Wtplus, color = "WT E+"), linetype = "solid", size = 0.7) +
    geom_point(aes(y = Wtplus, color = "WT E+"), shape = 16, size = 3) +
    labs(x = "Dni", y = "Sumaryczna liczba liści", title = "Liczba liści w czasie") +
    scale_y_continuous(limits =c(0, 210)) +
    scale_color_manual(
        values = c(
            "AT5G45470 E-" = "#A6CEE3",
            "AT5G45470 E+" = "#1F78B4",
            "WT E-" = "#B2DF8A",
            "WT E+" = "#33A02C"
        ),
        name = "",
        labels = c(
            "AT5G45470 E-" = "AT5G45470 E-",
            "AT5G45470 E+" = "AT5G45470 E+",
            "WT E-" = "WT E-",
            "WT E+" = "WT E+"
        )
    ) +
    theme(legend.position = "top") +
    theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + # Środkowanie tytułu
    theme(
        panel.background = element_rect(fill = "white"),  # Białe tło
        panel.grid.major = element_line(color = "lightgray", size = 0.5), # Szare linie siatki
        panel.grid.minor = element_blank()  # Wyłącz linie siatki pomocniczej
    )
```

```{r}
ggsave(filename = file.path(path, 'figures/plots/liscie70.png'), plot = liscie_plot, width = 12, height = 8)
```

```{r}
kwit_path_aov <- file.path(path, "pot_cultures/data/kwitnienie70_anova.ods")
liscie_path_aov <- file.path(path, "pot_cultures/data/liscie70_anova.ods")
```

```{r}
kwit_aov <- read_ods(kwit_path_aov)
liscie_aov <- read_ods(liscie_path_aov)
```


```{r}
anova <- aov(data = kwit_aov, formula = wynik ~ DNI * rodzaj)
summary(anova)
```

```{r}
TukeyHSD(anova)
```
Są różnice między Wtplus-70plus.

```{r}
anova2 <- aov(data = liscie_aov, formula = wynik ~ DNI * rodzaj)
summary(anova2)
```

```{r}
TukeyHSD(anova2)
```
Nie ma różnic.
