---
title: "AT5G45470 & AT545480 qPCR"
output: html.notebook
---

qPCR analysis and plots for my master thesis.

```{r}
require(ggplot2)
require(readxl)
```

Livak method:

```{r}
fold.70 <- c(3.28, 0.33, 0.92, 12.01, 29.38, 14.37)
fold.80 <- c(0.52, 0.7, 2.75, 10.71, 14.09, 3.96)
names <- c('E-3', 'E-4', 'E-5', 'E+2', 'E+3', 'E+4')
sd.70 <- c(1.56, 1.56, 1.56, 9.42, 9.42, 9.42)
sd.80 <- c(1.24, 1.24, 1.24, 5.15, 5.15, 5.15)
```

```{r}
df.70 <- data.frame(names, fold.70, sd.70)
```

```{r}
df.80 <- data.frame(names, fold.80)
```

```{r}
ggplot(data = df.70, aes(names, fold.70))+
  geom_bar(stat="identity")+
  labs(title = "Fold change dla genu AT5G545470", x = "Roślina", y = "Fold change")+
  geom_errorbar( aes(x=names, ymin=fold.70-sd.70, ymax=fold.70+sd.70), width=0.1, colour="black", alpha=0.9, size=0.5)
```

```{r}
ggplot(data = df.80, aes(names, fold.80))+
  geom_bar(stat="identity")+
  labs(title = "Fold change dla genu AT5G45480", x = "Roślina", y = "Fold change")+
  geom_errorbar( aes(x=names, ymin=fold.80-sd.80, ymax=fold.80+sd.80), width=0.1, colour="black", alpha=0.9, size=0.5)
```

```{r}
plant <- c(rep("E-", 3), rep("E+", 3), rep("E-", 3), rep("E+", 3))
goi <- c(rep("70", 6), rep("80", 6))
fold.change <- c(3.28, 0.33, 0.92, 12.01, 29.38, 14.37, 0.52, 0.7, 2.75, 10.71, 14.09, 3.96)
anova.df <- data.frame(plant, goi, fold.change)
anova.df
```

```{r}
fc.anova <- aov(fold.change ~ plant + goi, data=anova.df)
summary(fc.anova)
```

```{r}
TukeyHSD(fc.anova)
```

```{r}
ggplot(anova.df, aes(x=plant, y=fold.change, fill=goi)) +
  geom_boxplot(color="black", fill="grey33")+
  labs(title = "Sumaryczne fold change w zależności od inokulacji", x = "Roślina", y = "Fold change")
```

Pfaffl method:

```{r}
plant <- c(rep("70E-", 3), rep("70E+", 3), rep("80E-", 3), rep("80E+", 3))
fold.change <- c(3.28, 0.33, 0.92, 12.01, 29.38, 14.37, 0.52, 0.7, 2.75, 10.71, 14.09, 6.46)
df <- data.frame(plant, fold.change)
df
```

```{r}
means <- df %>%
  group_by(plant) %>% 
  summarise(fold.change = mean(fold.change))
means$error.bars <- c(9.42, 1.56, 5.14, 1.24)
means

bar_plot <- ggplot(df, aes(x = plant, y = fold.change, fill = plant)) +
  geom_bar(data=means, stat = "identity", alpha=0.8) +
  geom_point(alpha=0.8) +
  labs(x = "Grupa roślin", y = "Zmiana ekspresji genu") +
  scale_fill_manual(values = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C")) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey") +
  theme(legend.position = "none") +
  geom_errorbar(data=means, aes(ymin=fold.change - error.bars, ymax=fold.change+error.bars), width = 0.25)
bar_plot
```

```{r}
ggsave(filename = 'pfaffl.png',plot = bar_plot)
```

```{r}
t.test.70 <- t.test(df$fold.change[1:3],df$fold.change[4:6], var.equal = TRUE)
t.test.70
```

```{r}
t.test.80 <- t.test(df$fold.change[7:9],df$fold.change[10:12], var.equal = TRUE)
t.test.80
```
