---
title: "AT5G45470 & AT545480 qPCR"
output: html.notebook
---

qPCR analysis and plots for my master thesis.

```{r}
require(ggplot2)
require(readxl)
require(dplyr)
```

```{r}
plant <- c("70E-","70E+")
length <- c(8.91,5.24)
means <- data.frame(plant, length)
means$error.bars <- c(4.13, 1.8)
means

bar_plot <- ggplot(means, aes(x = plant, y = length, fill = plant)) +
  geom_bar(data=means, stat = "identity", alpha=0.8) +
  ggtitle("Zmiana ilości włośników w zależności od inokulacji i mutacji") +
  geom_point(alpha=0.8) +
  labs(x = "Grupa roślin", y = "Łączna długość korzenia") +
  scale_fill_manual(values = c("#A6CEE3", "#1F78B4")) +
  theme(legend.position = "none", text = element_text(size = 20)) +
  geom_errorbar(data=means, aes(ymin=length - error.bars, ymax=length+error.bars), width = 0.25) +
  theme(panel.background = element_rect(fill = "white"),  # Białe tło
        panel.grid.major = element_line(color = "lightgrey"), 
        legend.title.align = 0.5,# Szare osie siatki
        panel.grid.minor = element_blank())  # Usunięcie siatki podrzędnej

bar_plot
```

```{r}
ggsave(filename = 'wlosniki.png',plot = bar_plot, width = 12, height = 8)
```

p-value w t-teście dla grup nierównolicznych (70e+ i 70e-) wyniosła 0.41 - nie ma różnicy istotnej statystycznie.
