---
title: "analysis"
output: html_document
date: "2023-12-14"
---

```{r}
library(tidyverse)
library(broom)
library(dplyr)
library(reshape)
library(multcompView)
library(dotenv)
```

```{r}
load_dot_env(file = ".env")
```


```{r}  
path <- Sys.getenv("MY_PATH")
path
```

```{r}
file_path <- file.path(path, "fluorCAM/measurements/measurement2/concatenated_file.tsv")

data_all <- read.csv(file_path, sep = '\t')
colnames(data_all)
```


```{r}
# Kolumna z grupami
data_all$plant <- as.factor(data_all$plant)
data_all$inoculation <- as.factor(data_all$inoculation)
plant <- data_all$plant
inoculation <- data_all$inoculation
significant_columns <- list()

# Pętla do analizy wariancji dla każdej kolumny
for (column_name in colnames(data_all)) {
  if (column_name != "plant" & column_name != "inoculation") {  # Sprawdzamy kolumny inne niż 'plant' i 'inoculation'
    # Tworzymy formułę ANOVA
    formula <- as.formula(paste(column_name, "~ plant * inoculation"))

    # Przeprowadzamy ANOVA
    anova_result <- aov(formula, data = data_all)

    
    df_anova <- data.frame(summary(anova_result)[[1]])
    p_value_anova <- df_anova$Pr..F.[1]
    
    # Przeprowadzamy test Tukeya
    tukey_result <- TukeyHSD(anova_result)
    
     # Jeśli p-value jest mniejsze niż 0.05, dodaj nazwę kolumny do significant_columns
    if (p_value_anova < 0.05) {
      significant_columns[[length(significant_columns) + 1]] <- column_name
    }
  }
}
```

```{r}
significant_cols <- trimws(significant_columns)
significant_cols
```


```{r}
# Create a new column 'group'
data_all$group <- with(data_all, interaction(inoculation, plant, drop = TRUE))

# Convert 'group' to a numeric representation
data_all$group <- as.numeric(data_all$group) - 1

# Print the resulting data_all table
print(data_all)
```

```{r}
data_all$group <- as.factor(data_all$group)

# anova
anova <- aov(Rfd_Lss ~ group, data = data_all)

print(anova)

# Tukey's test
tukey <- TukeyHSD(anova)

print(tukey)

# compact letter display
cld <- multcompLetters4(anova, tukey)

# table with factors and 3rd quantile
dt <- group_by(data_all, group) %>%
  summarise(w=mean(Rfd_Lss), sd = sd(Rfd_Lss)) %>%
  arrange(desc(w))

# extracting the compact letter display and adding to the Tk table
cld <- as.data.frame.list(cld$group)
dt$cld <- cld$Letters


rfd_pomiar2 <- ggplot(dt, aes(group, w, fill = factor(group))) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_errorbar(aes(ymin = w - sd, ymax = w + sd), width = 0.2) +
  ggtitle("Rfd w zależności od grupy roślin, pomiar 2") +
  labs(x = "", y = "Rfd") +
  geom_text(aes(label = cld, y = w + sd), vjust = -0.5) +
  scale_fill_manual(
    values = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C"),
    breaks = c(0, 1, 2, 3),
    labels = c("AT5G45470 E-", "AT5G45470 E+", "WT E-", "WT"),
    name = ""
  ) +
  theme(legend.position = "top", text = element_text(size = 20)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "lightgray", size = 0.5),
    panel.grid.minor = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

```{r}
data_all$group <- as.factor(data_all$group)

# anova
anova <- aov(NPQ_Lss ~ group, data = data_all)

print(anova)

# Tukey's test
tukey <- TukeyHSD(anova)

print(tukey)

# compact letter display
cld <- multcompLetters4(anova, tukey)

# table with factors and 3rd quantile
dt <- group_by(data_all, group) %>%
  summarise(w=mean(NPQ_Lss), sd = sd(NPQ_Lss)) %>%
  arrange(desc(w))

# extracting the compact letter display and adding to the Tk table
cld <- as.data.frame.list(cld$group)
dt$cld <- cld$Letters


npq_pomiar2 <- ggplot(dt, aes(group, w, fill = factor(group))) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_errorbar(aes(ymin = w - sd, ymax = w + sd), width = 0.2) +
  ggtitle("NPQ w zależności od grupy roślin, pomiar 2") +
  labs(x = "", y = "NPQ") +
  geom_text(aes(label = cld, y = w + sd), vjust = -0.5) +
  scale_fill_manual(
    values = c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C"),
    breaks = c(0, 1, 2, 3),
    labels = c("AT5G45470 E-", "AT5G45470 E+", "WT E-", "WT"),
    name = ""
  ) +
  theme(legend.position = "top", text = element_text(size = 20)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_line(color = "lightgray", size = 0.5),
    panel.grid.minor = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

ggsave(filename = file.path(path, '/figures/plots/rfd_lss_pomiar2.png'), plot = rfd_pomiar1, width = 12, height = 8)
ggsave(filename = file.path(path, 'figures/plots/npq_lss_pomiar2.png'), plot = npq_pomiar1, width = 12, height = 8)





